all: solution

solution: solution.cpp
	gcc -o libsolution.so solution.cpp -shared -fPIC


#solution: solution.o
#	gcc -o libsolution.so solution.o -shared

#solution.o: solution.o
#	gcc -c solution.cpp -std=c11 -fPIC

# gcc -c solution.c -std=c11 -fPIC
# gcc -o libsolution.so solution.o -shared